import { describe, expect, it } from 'bun:test';
import type { AgentSession } from '@earendil-works/pi-coding-agent';
import {
  applySystemPromptAppend,
  applySystemPromptOverride,
  shouldPreservePiSystemPrompt,
} from './system-prompt-override.ts';

/**
 * Regression contract for mkagent-oss#648.
 *
 * Pi SDK 0.80.6's `session.prompt()` resets `agent.state.systemPrompt` to
 * `_baseSystemPrompt` on every turn (agent-session.js ~L796), and
 * `_baseSystemPrompt` itself can be regenerated by the SDK via
 * `_rebuildSystemPrompt()` when tools change. To survive both paths we must
 * stamp ALL THREE internals on the session — dropping any one of them
 * re-introduces the original bug:
 *   - `agent.state.systemPrompt` — what the next agent_loop turn ships to the LLM
 *   - `_baseSystemPrompt` — what the SDK falls back to when no extension override
 *   - `_rebuildSystemPrompt` — what the SDK calls on tool/resource rebuilds
 *
 * Pattern matches OpenClaw's `applySystemPromptOverrideToSession`.
 */

type StampedSession = {
  agent: { state: { systemPrompt?: string } };
  _baseSystemPrompt?: string;
  _rebuildSystemPrompt?: (toolNames: string[]) => string;
};

function makeFakeSession(): StampedSession {
  return {
    agent: { state: {} },
  };
}

describe('applySystemPromptOverride', () => {
  it('stamps state.systemPrompt', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'MKAGENT_PROMPT');
    expect(session.agent.state.systemPrompt).toBe('MKAGENT_PROMPT');
  });

  it('stamps the private _baseSystemPrompt field so session.prompt() reset survives', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'MKAGENT_PROMPT');
    expect(session._baseSystemPrompt).toBe('MKAGENT_PROMPT');
  });

  it('replaces _rebuildSystemPrompt with a constant function so tool-change rebuilds survive', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'MKAGENT_PROMPT');
    expect(typeof session._rebuildSystemPrompt).toBe('function');
    // Must return our prompt regardless of which tool names the SDK passes in.
    expect(session._rebuildSystemPrompt!(['read', 'bash'])).toBe('MKAGENT_PROMPT');
    expect(session._rebuildSystemPrompt!([])).toBe('MKAGENT_PROMPT');
  });

  it('overwrites previously stamped values on a re-application', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'FIRST');
    applySystemPromptOverride(session as unknown as AgentSession, 'SECOND');
    expect(session.agent.state.systemPrompt).toBe('SECOND');
    expect(session._baseSystemPrompt).toBe('SECOND');
    expect(session._rebuildSystemPrompt!([])).toBe('SECOND');
  });
});

describe('applySystemPromptAppend', () => {
  it('preserves the Pi default prompt and appends MkAgent instructions', () => {
    const session = makeFakeSession();
    session._baseSystemPrompt = 'PI_DEFAULT';
    session.agent.state.systemPrompt = 'PI_DEFAULT';

    applySystemPromptAppend(session as unknown as AgentSession, 'MKAGENT_PROMPT');

    expect(session.agent.state.systemPrompt).toBe('PI_DEFAULT\n\nMKAGENT_PROMPT');
    expect(session._baseSystemPrompt).toBe('PI_DEFAULT\n\nMKAGENT_PROMPT');
  });

  it('retains tool-aware Pi prompt rebuilds', () => {
    const session = makeFakeSession();
    session._baseSystemPrompt = 'PI_DEFAULT';
    session._rebuildSystemPrompt = toolNames => `PI_TOOLS:${toolNames.join(',')}`;

    applySystemPromptAppend(session as unknown as AgentSession, 'MKAGENT_PROMPT');

    expect(session._rebuildSystemPrompt!(['read', 'bash']))
      .toBe('PI_TOOLS:read,bash\n\nMKAGENT_PROMPT');
  });

  it('replaces the appended instructions without duplicating prior values', () => {
    const session = makeFakeSession();
    session._baseSystemPrompt = 'PI_DEFAULT';
    session._rebuildSystemPrompt = toolNames => `PI_TOOLS:${toolNames.join(',')}`;

    applySystemPromptAppend(session as unknown as AgentSession, 'FIRST');
    expect(session._rebuildSystemPrompt!(['read']))
      .toBe('PI_TOOLS:read\n\nFIRST');

    applySystemPromptAppend(session as unknown as AgentSession, 'SECOND');

    expect(session.agent.state.systemPrompt).toBe('PI_TOOLS:read\n\nSECOND');
    expect(session._rebuildSystemPrompt!(['bash']))
      .toBe('PI_TOOLS:bash\n\nSECOND');
  });
});

describe('shouldPreservePiSystemPrompt', () => {
  it('enables append mode only for configured custom Anthropic endpoints', () => {
    expect(shouldPreservePiSystemPrompt(
      'https://gateway.example.test',
      { api: 'anthropic-messages' },
    )).toBe(true);
    expect(shouldPreservePiSystemPrompt(
      'https://gateway.example.test',
      { api: 'openai-completions' },
    )).toBe(false);
    expect(shouldPreservePiSystemPrompt(undefined, { api: 'anthropic-messages' }))
      .toBe(false);
    expect(shouldPreservePiSystemPrompt('https://gateway.example.test', undefined))
      .toBe(false);
  });
});
